#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
基于 ReportLab 的暗色主题音乐编年史 PDF 生成器
用法: python generate_pdf_reportlab.py <analysis_data.json> <music_report.md> <output.pdf>

设计特点：
- 深色背景 (#0D1117) + 青/紫/金/粉多色点缀
- 顶部装饰线 + 圆点端点
- 数据柱状图可视化
- 引用块高亮样式
- 不依赖浏览器，适合服务器环境

依赖: pip install reportlab
"""

import os
import sys
import re
import json
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Color Palette
BG_DARK = HexColor('#0D1117')
BG_CARD = HexColor('#161B22')
ACCENT_CYAN = HexColor('#58A6FF')
ACCENT_PURPLE = HexColor('#BC8CFF')
ACCENT_GOLD = HexColor('#F0C674')
ACCENT_PINK = HexColor('#FF7B72')
TEXT_PRIMARY = HexColor('#E6EDF3')
TEXT_SECONDARY = HexColor('#8B949E')
TEXT_DIM = HexColor('#484F58')
DIVIDER = HexColor('#21262D')
HIGHLIGHT_BG = HexColor('#1C2128')

# Layout
PAGE_W, PAGE_H = A4
MARGIN_L = 25 * mm
MARGIN_R = 25 * mm
MARGIN_T = 20 * mm
CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R

# Font setup
cn_font = 'Helvetica'
cn_bold = 'Helvetica-Bold'

font_candidates = [
    ('/System/Library/Fonts/PingFang.ttc', 'PingFang', 0),
    ('/System/Library/Fonts/STHeiti Light.ttc', 'STHeiti', 0),
    ('/System/Library/Fonts/Hiragino Sans GB.ttc', 'Hiragino', 0),
    ('/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc', 'NotoSansCJK', 0),
]

for path, name, idx in font_candidates:
    if os.path.exists(path):
        try:
            pdfmetrics.registerFont(TTFont(name, path, subfontIndex=idx))
            cn_font = name
            cn_bold = name
            break
        except Exception:
            continue


class MusicPDF:
    def __init__(self, filename, title='音乐编年史'):
        self.c = canvas.Canvas(filename, pagesize=A4)
        self.c.setTitle(title)
        self.page_num = 0
        self.y = PAGE_H - MARGIN_T

    def _bg(self):
        self.c.setFillColor(BG_DARK)
        self.c.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)

    def _top_line(self):
        self.c.setStrokeColor(ACCENT_CYAN)
        self.c.setLineWidth(0.5)
        self.c.line(MARGIN_L, PAGE_H - 15*mm, PAGE_W - MARGIN_R, PAGE_H - 15*mm)
        self.c.setFillColor(ACCENT_CYAN)
        self.c.circle(MARGIN_L, PAGE_H - 15*mm, 1.5, fill=1, stroke=0)
        self.c.circle(PAGE_W - MARGIN_R, PAGE_H - 15*mm, 1.5, fill=1, stroke=0)

    def _page_num(self):
        self.page_num += 1
        if self.page_num > 1:
            self.c.setFont(cn_font, 8)
            self.c.setFillColor(TEXT_DIM)
            self.c.drawCentredString(PAGE_W/2, 12*mm, f'— {self.page_num} —')

    def new_page(self):
        self.c.showPage()
        self._bg()
        self._top_line()
        self._page_num()
        self.y = PAGE_H - MARGIN_T - 10*mm

    def check_space(self, needed=35*mm):
        if self.y < needed:
            self.new_page()

    def cover(self, title='音乐编年史', subtitle='', meta=''):
        self._bg()
        # Grid decoration
        self.c.setStrokeColor(HexColor('#1C2128'))
        self.c.setLineWidth(0.3)
        for i in range(0, int(PAGE_W), 20):
            self.c.line(i, PAGE_H, i, PAGE_H - 80*mm)
        for j in range(int(PAGE_H - 80*mm), int(PAGE_H), 20):
            self.c.line(0, j, PAGE_W, j)

        y = PAGE_H - 120*mm
        self.c.setFont(cn_bold, 36)
        self.c.setFillColor(TEXT_PRIMARY)
        self.c.drawCentredString(PAGE_W/2, y, title)

        if subtitle:
            self.c.setFont(cn_font, 14)
            self.c.setFillColor(ACCENT_CYAN)
            self.c.drawCentredString(PAGE_W/2, y - 20*mm, subtitle)

        if meta:
            self.c.setFont(cn_font, 10)
            self.c.setFillColor(TEXT_SECONDARY)
            self.c.drawCentredString(PAGE_W/2, y - 35*mm, meta)

        self.c.setFont(cn_font, 8)
        self.c.setFillColor(TEXT_DIM)
        self.c.drawCentredString(PAGE_W/2, 35*mm, 'Generated by netease-music-chronicle')

        self.c.setStrokeColor(ACCENT_GOLD)
        self.c.setLineWidth(0.8)
        self.c.line(PAGE_W/2 - 40*mm, 30*mm, PAGE_W/2 + 40*mm, 30*mm)
        self.page_num += 1

    def section(self, title, subtitle=None, color=ACCENT_CYAN):
        self.check_space(60*mm)
        self.c.setFillColor(color)
        self.c.rect(MARGIN_L, self.y - 2, 3, 18, fill=1, stroke=0)
        self.c.setFont(cn_bold, 18)
        self.c.setFillColor(TEXT_PRIMARY)
        self.c.drawString(MARGIN_L + 10, self.y, title)
        if subtitle:
            self.y -= 18
            self.c.setFont(cn_font, 10)
            self.c.setFillColor(TEXT_SECONDARY)
            self.c.drawString(MARGIN_L + 10, self.y, subtitle)
        self.y -= 25

    def sub(self, title, color=ACCENT_GOLD):
        self.check_space(40*mm)
        self.c.setFont(cn_bold, 13)
        self.c.setFillColor(color)
        self.c.drawString(MARGIN_L + 5, self.y, title)
        self.y -= 18

    def text(self, t, indent=0, bold=False, color=None, size=10):
        self.check_space()
        font = cn_bold if bold else cn_font
        clr = color or TEXT_PRIMARY
        self.c.setFont(font, size)
        self.c.setFillColor(clr)
        x = MARGIN_L + indent
        max_chars = int((CONTENT_W - indent) / (size * 0.55))
        while len(t) > max_chars:
            self.check_space()
            self.c.setFont(font, size)
            self.c.setFillColor(clr)
            self.c.drawString(x, self.y, t[:max_chars])
            t = t[max_chars:]
            self.y -= size * 1.6
        if t:
            self.check_space()
            self.c.setFont(font, size)
            self.c.setFillColor(clr)
            self.c.drawString(x, self.y, t)
            self.y -= size * 1.6

    def quote(self, t):
        self.check_space(50*mm)
        max_chars = int((CONTENT_W - 20*mm) / (9.5 * 0.55))
        lines = []
        temp = t
        while len(temp) > max_chars:
            lines.append(temp[:max_chars])
            temp = temp[max_chars:]
        if temp:
            lines.append(temp)
        block_h = len(lines) * 14 + 16
        self.c.setFillColor(HIGHLIGHT_BG)
        self.c.roundRect(MARGIN_L, self.y - block_h + 14, CONTENT_W, block_h, 4, fill=1, stroke=0)
        self.c.setFillColor(ACCENT_PURPLE)
        self.c.rect(MARGIN_L + 2, self.y - block_h + 18, 2, block_h - 8, fill=1, stroke=0)
        self.c.setFont(cn_font, 9.5)
        self.c.setFillColor(ACCENT_PURPLE)
        for line in lines:
            self.c.drawString(MARGIN_L + 12, self.y, line)
            self.y -= 14
        self.y -= 10

    def bar(self, label, value, max_val, color=ACCENT_CYAN):
        self.check_space()
        self.c.setFont(cn_font, 9)
        self.c.setFillColor(TEXT_SECONDARY)
        self.c.drawString(MARGIN_L + 5, self.y, label)
        bx = MARGIN_L + 35*mm
        bw = CONTENT_W - 40*mm - 20*mm
        self.c.setFillColor(DIVIDER)
        self.c.roundRect(bx, self.y - 1, bw, 8, 3, fill=1, stroke=0)
        self.c.setFillColor(color)
        ratio = min(value / max(max_val, 1), 1.0)
        self.c.roundRect(bx, self.y - 1, bw * ratio, 8, 3, fill=1, stroke=0)
        self.c.setFont(cn_font, 8)
        self.c.setFillColor(TEXT_PRIMARY)
        self.c.drawRightString(PAGE_W - MARGIN_R, self.y, str(value))
        self.y -= 18

    def divider(self):
        self.y -= 5
        self.c.setStrokeColor(DIVIDER)
        self.c.setLineWidth(0.5)
        self.c.line(MARGIN_L + 10, self.y, PAGE_W - MARGIN_R - 10, self.y)
        self.y -= 10

    def sp(self, h=5):
        self.y -= h

    def save(self):
        self.c.save()
        print(f'\n✅ PDF 已生成: {self.c._filename}')
        print(f'   共 {self.page_num} 页')


def build_from_markdown(md_path, output_path):
    """从Markdown报告直接生成暗色PDF"""
    with open(md_path, 'r', encoding='utf-8') as f:
        md_content = f.read()

    # 提取标题
    title_match = re.search(r'^# (.+)$', md_content, re.MULTILINE)
    title = title_match.group(1) if title_match else '音乐编年史'

    if '：' in title:
        parts = title.split('：', 1)
        cover_title = '音乐编年史'
        cover_sub = parts[1] if len(parts) > 1 else ''
    else:
        cover_title = '音乐编年史'
        cover_sub = title

    pdf = MusicPDF(output_path, title)
    pdf.cover(cover_title, cover_sub)

    # 解析Markdown并渲染
    lines = md_content.split('\n')
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('# '):
            continue  # 跳过主标题（已在封面）
        elif stripped.startswith('## '):
            pdf.new_page()
            pdf.section(stripped[3:])
        elif stripped.startswith('### '):
            pdf.sub(stripped[4:])
        elif stripped == '---':
            pdf.divider()
        elif stripped == '':
            pdf.sp(6)
        elif stripped.startswith('**') and stripped.endswith('**'):
            # 纯粗体行
            text = stripped[2:-2]
            pdf.text(text, bold=True)
        else:
            # 普通文本（去除markdown格式标记）
            text = re.sub(r'\*\*(.+?)\*\*', r'\1', stripped)
            text = re.sub(r'\*(.+?)\*', r'\1', text)
            pdf.text(text)

    pdf.save()


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("用法: python generate_pdf_reportlab.py <music_report.md> <output.pdf>")
        print("  或: python generate_pdf_reportlab.py <analysis_data.json> <music_report.md> <output.pdf>")
        sys.exit(1)

    if len(sys.argv) == 3:
        build_from_markdown(sys.argv[1], sys.argv[2])
    else:
        # 兼容三参数模式（analysis_data.json, md, output）
        build_from_markdown(sys.argv[2], sys.argv[3])
